'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class allProducts
    
    '''<summary>
    '''getPhones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents getPhones As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOS As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrand As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBrand As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblNetworkMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNetworkMode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlNetworkMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNetworkMode As Global.System.Web.UI.WebControls.DropDownList
End Class
