'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace cr.fi.bccr.indicadoreseconomicos
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="wsIndicadoresEconomicosSoap", [Namespace]:="http://ws.sdde.bccr.fi.cr")>  _
    Partial Public Class wsIndicadoresEconomicos
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ObtenerIndicadoresEconomicosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObtenerIndicadoresEconomicosXMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Testing.My.MySettings.Default.Testing_cr_fi_bccr_indicadoreseconomicos_wsIndicadoresEconomicos
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ObtenerIndicadoresEconomicosCompleted As ObtenerIndicadoresEconomicosCompletedEventHandler
        
        '''<remarks/>
        Public Event ObtenerIndicadoresEconomicosXMLCompleted As ObtenerIndicadoresEconomicosXMLCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicos", RequestNamespace:="http://ws.sdde.bccr.fi.cr", ResponseNamespace:="http://ws.sdde.bccr.fi.cr", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtenerIndicadoresEconomicos(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ObtenerIndicadoresEconomicos", New Object() {tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtenerIndicadoresEconomicosAsync(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String)
            Me.ObtenerIndicadoresEconomicosAsync(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtenerIndicadoresEconomicosAsync(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String, ByVal userState As Object)
            If (Me.ObtenerIndicadoresEconomicosOperationCompleted Is Nothing) Then
                Me.ObtenerIndicadoresEconomicosOperationCompleted = AddressOf Me.OnObtenerIndicadoresEconomicosOperationCompleted
            End If
            Me.InvokeAsync("ObtenerIndicadoresEconomicos", New Object() {tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles}, Me.ObtenerIndicadoresEconomicosOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtenerIndicadoresEconomicosOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtenerIndicadoresEconomicosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtenerIndicadoresEconomicosCompleted(Me, New ObtenerIndicadoresEconomicosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicosXML", RequestNamespace:="http://ws.sdde.bccr.fi.cr", ResponseNamespace:="http://ws.sdde.bccr.fi.cr", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtenerIndicadoresEconomicosXML(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As String
            Dim results() As Object = Me.Invoke("ObtenerIndicadoresEconomicosXML", New Object() {tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtenerIndicadoresEconomicosXMLAsync(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String)
            Me.ObtenerIndicadoresEconomicosXMLAsync(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtenerIndicadoresEconomicosXMLAsync(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String, ByVal userState As Object)
            If (Me.ObtenerIndicadoresEconomicosXMLOperationCompleted Is Nothing) Then
                Me.ObtenerIndicadoresEconomicosXMLOperationCompleted = AddressOf Me.OnObtenerIndicadoresEconomicosXMLOperationCompleted
            End If
            Me.InvokeAsync("ObtenerIndicadoresEconomicosXML", New Object() {tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles}, Me.ObtenerIndicadoresEconomicosXMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtenerIndicadoresEconomicosXMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtenerIndicadoresEconomicosXMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtenerIndicadoresEconomicosXMLCompleted(Me, New ObtenerIndicadoresEconomicosXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub ObtenerIndicadoresEconomicosCompletedEventHandler(ByVal sender As Object, ByVal e As ObtenerIndicadoresEconomicosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtenerIndicadoresEconomicosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub ObtenerIndicadoresEconomicosXMLCompletedEventHandler(ByVal sender As Object, ByVal e As ObtenerIndicadoresEconomicosXMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtenerIndicadoresEconomicosXMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
