'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ClientServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ClientServiceReference.IClientService")>  _
    Public Interface IClientService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClientService/insertClient", ReplyAction:="http://tempuri.org/IClientService/insertClientResponse")>  _
        Function insertClient(ByVal client As String, ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClientService/insertClient", ReplyAction:="http://tempuri.org/IClientService/insertClientResponse")>  _
        Function insertClientAsync(ByVal client As String, ByVal key As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClientService/updateClient", ReplyAction:="http://tempuri.org/IClientService/updateClientResponse")>  _
        Function updateClient(ByVal client As String, ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClientService/updateClient", ReplyAction:="http://tempuri.org/IClientService/updateClientResponse")>  _
        Function updateClientAsync(ByVal client As String, ByVal key As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClientService/deleteClient", ReplyAction:="http://tempuri.org/IClientService/deleteClientResponse")>  _
        Function deleteClient(ByVal idClient As String, ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClientService/deleteClient", ReplyAction:="http://tempuri.org/IClientService/deleteClientResponse")>  _
        Function deleteClientAsync(ByVal idClient As String, ByVal key As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClientService/verifyExistsClient", ReplyAction:="http://tempuri.org/IClientService/verifyExistsClientResponse")>  _
        Function verifyExistsClient(ByVal client As String, ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClientService/verifyExistsClient", ReplyAction:="http://tempuri.org/IClientService/verifyExistsClientResponse")>  _
        Function verifyExistsClientAsync(ByVal client As String, ByVal key As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClientService/getClient", ReplyAction:="http://tempuri.org/IClientService/getClientResponse")>  _
        Function getClient(ByVal nameUser As String, ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IClientService/getClient", ReplyAction:="http://tempuri.org/IClientService/getClientResponse")>  _
        Function getClientAsync(ByVal nameUser As String, ByVal key As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IClientServiceChannel
        Inherits ClientServiceReference.IClientService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ClientServiceClient
        Inherits System.ServiceModel.ClientBase(Of ClientServiceReference.IClientService)
        Implements ClientServiceReference.IClientService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function insertClient(ByVal client As String, ByVal key As String) As String Implements ClientServiceReference.IClientService.insertClient
            Return MyBase.Channel.insertClient(client, key)
        End Function
        
        Public Function insertClientAsync(ByVal client As String, ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements ClientServiceReference.IClientService.insertClientAsync
            Return MyBase.Channel.insertClientAsync(client, key)
        End Function
        
        Public Function updateClient(ByVal client As String, ByVal key As String) As String Implements ClientServiceReference.IClientService.updateClient
            Return MyBase.Channel.updateClient(client, key)
        End Function
        
        Public Function updateClientAsync(ByVal client As String, ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements ClientServiceReference.IClientService.updateClientAsync
            Return MyBase.Channel.updateClientAsync(client, key)
        End Function
        
        Public Function deleteClient(ByVal idClient As String, ByVal key As String) As String Implements ClientServiceReference.IClientService.deleteClient
            Return MyBase.Channel.deleteClient(idClient, key)
        End Function
        
        Public Function deleteClientAsync(ByVal idClient As String, ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements ClientServiceReference.IClientService.deleteClientAsync
            Return MyBase.Channel.deleteClientAsync(idClient, key)
        End Function
        
        Public Function verifyExistsClient(ByVal client As String, ByVal key As String) As String Implements ClientServiceReference.IClientService.verifyExistsClient
            Return MyBase.Channel.verifyExistsClient(client, key)
        End Function
        
        Public Function verifyExistsClientAsync(ByVal client As String, ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements ClientServiceReference.IClientService.verifyExistsClientAsync
            Return MyBase.Channel.verifyExistsClientAsync(client, key)
        End Function
        
        Public Function getClient(ByVal nameUser As String, ByVal key As String) As String Implements ClientServiceReference.IClientService.getClient
            Return MyBase.Channel.getClient(nameUser, key)
        End Function
        
        Public Function getClientAsync(ByVal nameUser As String, ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements ClientServiceReference.IClientService.getClientAsync
            Return MyBase.Channel.getClientAsync(nameUser, key)
        End Function
    End Class
End Namespace
