'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace BrandServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="BrandServiceReference.IBrandService")>  _
    Public Interface IBrandService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBrandService/insertBrand", ReplyAction:="http://tempuri.org/IBrandService/insertBrandResponse")>  _
        Function insertBrand(ByVal idBrand As String, ByVal name As String, ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBrandService/insertBrand", ReplyAction:="http://tempuri.org/IBrandService/insertBrandResponse")>  _
        Function insertBrandAsync(ByVal idBrand As String, ByVal name As String, ByVal key As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBrandService/updateBrand", ReplyAction:="http://tempuri.org/IBrandService/updateBrandResponse")>  _
        Function updateBrand(ByVal idBrand As String, ByVal name As String, ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBrandService/updateBrand", ReplyAction:="http://tempuri.org/IBrandService/updateBrandResponse")>  _
        Function updateBrandAsync(ByVal idBrand As String, ByVal name As String, ByVal key As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBrandService/deleteBrand", ReplyAction:="http://tempuri.org/IBrandService/deleteBrandResponse")>  _
        Function deleteBrand(ByVal idBrand As String, ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBrandService/deleteBrand", ReplyAction:="http://tempuri.org/IBrandService/deleteBrandResponse")>  _
        Function deleteBrandAsync(ByVal idBrand As String, ByVal key As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBrandService/getAllBrands", ReplyAction:="http://tempuri.org/IBrandService/getAllBrandsResponse")>  _
        Function getAllBrands(ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBrandService/getAllBrands", ReplyAction:="http://tempuri.org/IBrandService/getAllBrandsResponse")>  _
        Function getAllBrandsAsync(ByVal key As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBrandService/getBrandById", ReplyAction:="http://tempuri.org/IBrandService/getBrandByIdResponse")>  _
        Function getBrandById(ByVal idBrand As String, ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBrandService/getBrandById", ReplyAction:="http://tempuri.org/IBrandService/getBrandByIdResponse")>  _
        Function getBrandByIdAsync(ByVal idBrand As String, ByVal key As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IBrandServiceChannel
        Inherits BrandServiceReference.IBrandService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BrandServiceClient
        Inherits System.ServiceModel.ClientBase(Of BrandServiceReference.IBrandService)
        Implements BrandServiceReference.IBrandService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function insertBrand(ByVal idBrand As String, ByVal name As String, ByVal key As String) As String Implements BrandServiceReference.IBrandService.insertBrand
            Return MyBase.Channel.insertBrand(idBrand, name, key)
        End Function
        
        Public Function insertBrandAsync(ByVal idBrand As String, ByVal name As String, ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements BrandServiceReference.IBrandService.insertBrandAsync
            Return MyBase.Channel.insertBrandAsync(idBrand, name, key)
        End Function
        
        Public Function updateBrand(ByVal idBrand As String, ByVal name As String, ByVal key As String) As String Implements BrandServiceReference.IBrandService.updateBrand
            Return MyBase.Channel.updateBrand(idBrand, name, key)
        End Function
        
        Public Function updateBrandAsync(ByVal idBrand As String, ByVal name As String, ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements BrandServiceReference.IBrandService.updateBrandAsync
            Return MyBase.Channel.updateBrandAsync(idBrand, name, key)
        End Function
        
        Public Function deleteBrand(ByVal idBrand As String, ByVal key As String) As String Implements BrandServiceReference.IBrandService.deleteBrand
            Return MyBase.Channel.deleteBrand(idBrand, key)
        End Function
        
        Public Function deleteBrandAsync(ByVal idBrand As String, ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements BrandServiceReference.IBrandService.deleteBrandAsync
            Return MyBase.Channel.deleteBrandAsync(idBrand, key)
        End Function
        
        Public Function getAllBrands(ByVal key As String) As String Implements BrandServiceReference.IBrandService.getAllBrands
            Return MyBase.Channel.getAllBrands(key)
        End Function
        
        Public Function getAllBrandsAsync(ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements BrandServiceReference.IBrandService.getAllBrandsAsync
            Return MyBase.Channel.getAllBrandsAsync(key)
        End Function
        
        Public Function getBrandById(ByVal idBrand As String, ByVal key As String) As String Implements BrandServiceReference.IBrandService.getBrandById
            Return MyBase.Channel.getBrandById(idBrand, key)
        End Function
        
        Public Function getBrandByIdAsync(ByVal idBrand As String, ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements BrandServiceReference.IBrandService.getBrandByIdAsync
            Return MyBase.Channel.getBrandByIdAsync(idBrand, key)
        End Function
    End Class
End Namespace
