'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SalePhoneServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SalePhoneServiceReference.ISalePhoneService")>  _
    Public Interface ISalePhoneService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISalePhoneService/registerSale", ReplyAction:="http://tempuri.org/ISalePhoneService/registerSaleResponse")>  _
        Function registerSale(ByVal idClient As String, ByVal phones As String, ByVal total As String, ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ISalePhoneService/registerSale", ReplyAction:="http://tempuri.org/ISalePhoneService/registerSaleResponse")>  _
        Function registerSaleAsync(ByVal idClient As String, ByVal phones As String, ByVal total As String, ByVal key As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISalePhoneServiceChannel
        Inherits SalePhoneServiceReference.ISalePhoneService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SalePhoneServiceClient
        Inherits System.ServiceModel.ClientBase(Of SalePhoneServiceReference.ISalePhoneService)
        Implements SalePhoneServiceReference.ISalePhoneService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function registerSale(ByVal idClient As String, ByVal phones As String, ByVal total As String, ByVal key As String) As String Implements SalePhoneServiceReference.ISalePhoneService.registerSale
            Return MyBase.Channel.registerSale(idClient, phones, total, key)
        End Function
        
        Public Function registerSaleAsync(ByVal idClient As String, ByVal phones As String, ByVal total As String, ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements SalePhoneServiceReference.ISalePhoneService.registerSaleAsync
            Return MyBase.Channel.registerSaleAsync(idClient, phones, total, key)
        End Function
    End Class
End Namespace
